import os

IS_PRODUCTION = not os.environ.get('SERVER_SOFTWARE', '').startswith('Devel')

LEGACY_MESSENGER_URL = ''
MESSENGER_DEFAULTS = []
AUTHOR_EMAIL = 'user@local.com'
APPLICATION_ID = 'test-app'
GITHUB_REPOSITORY = 'https://github.com/phistuck/test-app/'
APPLICATION_TITLE = 'Test App'
COPYRIGHT_HOLDER = 'tester'
COPYRIGHT_YEAR_RANGE = '2017'
GOOGLE_SITE_VERIFICATION = ''
VERIFY_V1 = ''

try:
 from configuration import CUSTOM_APPLICATION_ID, \
  CUSTOM_AUTHOR_EMAIL, CUSTOM_LEGACY_MESSENGER_URL, \
  CUSTOM_MESSENGER_DEFAULTS, CUSTOM_GITHUB_REPOSITORY, \
  CUSTOM_APPLICATION_TITLE, CUSTOM_COPYRIGHT_YEAR_RANGE, \
  CUSTOM_COPYRIGHT_HOLDER
 AUTHOR_EMAIL = CUSTOM_AUTHOR_EMAIL or AUTHOR_EMAIL
 APPLICATION_ID = CUSTOM_APPLICATION_ID or APPLICATION_ID
 LEGACY_MESSENGER_URL = CUSTOM_LEGACY_MESSENGER_URL or LEGACY_MESSENGER_URL
 MESSENGER_DEFAULTS = CUSTOM_MESSENGER_DEFAULTS or MESSENGER_DEFAULTS
 GITHUB_REPOSITORY = CUSTOM_GITHUB_REPOSITORY or GITHUB_REPOSITORY
 APPLICATION_TITLE = CUSTOM_APPLICATION_TITLE or APPLICATION_TITLE
 COPYRIGHT_YEAR_RANGE = CUSTOM_COPYRIGHT_YEAR_RANGE or COPYRIGHT_YEAR_RANGE
 COPYRIGHT_HOLDER = CUSTOM_COPYRIGHT_HOLDER or COPYRIGHT_HOLDER
 GOOGLE_SITE_VERIFICATION = CUSTOM_GOOGLE_SITE_VERIFICATION or GOOGLE_SITE_VERIFICATION
 VERIFY_V1 = CUSTOM_VERIFY_V1 or VERIFY_V1
except:
 import logging
 logging.info('No custom configuration defined, or there was an error loading it.')

HOST_NAME = '%s.appspot.com' % APPLICATION_ID
PROTOCOL = 'https'
EMAIL_HOST_NAME = '%s.appspotmail.com' % APPLICATION_ID
BUG_DATABASE_NO_REPLY_EMAIL = 'bug-database-no-reply@%s' % EMAIL_HOST_NAME
NO_REPLY_EMAIL = 'no-reply@%s' % EMAIL_HOST_NAME

EXTENSION_GALLERY = 'https://chrome.google.com/extensions/detail/'

if not IS_PRODUCTION:
 HOST_NAME = 'localhost:8080'
 PROTOCOL = 'http'
ORIGIN = '%s://%s' % (PROTOCOL, HOST_NAME)
TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), 'content-template.html')